# Generated by Django 5.1.4 on 2026-01-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_document_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
